---
- name: instal php
  yum:
    name: php56
    state: latest
    enablerepo: remi,remi-php56

- name: instal php-mbstring
  yum:
    name: php56-php-mbstring

- name: instal php-pdo
  yum:
    name: php56-php-pdo
    state: latest

- name: instal php-mbstring
  yum:
    name: php56-php-mysqlnd
    state: latest

- name: instal php-bcmath
  yum:
    name: php56-php-bcmath
    state: latest

- name: instal php-fpm
  yum:
    name: php56-php-fpm
    state: latest
    enablerepo: remi,remi-php56

- name: start php-fpm
  service:
    name: php56-php-fpm
    state: started
    enabled: true

- name: enable php56
  template:
    src: enablephp56.sh
    dest: /etc/profile.d/enablephp56.sh
