---
- name: Remove PHP 7.2
  yum:
    name: php72*
    state: absent

- name: instal php
  yum:
    name: php56
    state: latest
    enablerepo: remi,remi-php56

- name: instal php-mbstring
  yum:
    name: php56-php-mbstring

- name: instal php-pdo
  yum:
    name: php56-php-pdo
    state: latest

- name: instal php-mbstring
  yum:
    name: php56-php-mysqlnd
    state: latest

- name: instal php-intl
  yum:
    name: php56-php-intl
    state: latest

- name: instal php-bcmath
  yum:
    name: php56-php-bcmath
    state: latest

- name: instal php-soap
  yum:
    name: php56-php-soap
    state: latest

- name: instal php-xdebug
  yum:
    name: php56-php-pecl-xdebug
    state: latest

- name: instal php-fpm
  yum:
    name: php56-php-fpm
    state: latest
    enablerepo: remi,remi-php56

- name: php.ini file
  template:
    src: php.ini
    dest: /opt/remi/php56/root/etc/php.ini

- name: www.cnf file
  template:
    src: www.conf
    dest: /opt/remi/php56/root/etc/php-fpm.d/www.conf

- name: set access log file
  file:
    state: directory
    path: /var/log/php-fpm
    mode: 0777

- name: set access log file
  file:
    state: touch
    dest: /var/log/php-fpm/access.log
    mode: 0777

- name: set error log file
  file:
    state: touch
    dest: /var/log/php-fpm/error.log
    mode: 0777

- name: set slow log file
  file:
    state: touch
    dest: /var/log/php-fpm/slow.log
    mode: 0777

- name: start php-fpm
  service:
    name: php56-php-fpm
    state: started
    enabled: true

- name: enable php56
  template:
    src: enablephp56.sh
    dest: /etc/profile.d/enablephp56.sh
