---
- hosts: all
  become: true
  become_user: root
  roles:
  - yum
  - mysql-57
  - { role: php-56, when: php_version == 5.6 }
  - { role: php-72, when: php_version == 7.2 }
  - nodejs
  - nginx
  - composer
  - shell
